#ifndef BISON_GRAMMAR_TAB_H
# define BISON_GRAMMAR_TAB_H

# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
# define	ICE_STORM_HELP	257
# define	ICE_STORM_EXIT	258
# define	ICE_STORM_CREATE	259
# define	ICE_STORM_DESTROY	260
# define	ICE_STORM_LIST	261
# define	ICE_STORM_LINK	262
# define	ICE_STORM_UNLINK	263
# define	ICE_STORM_GRAPH	264
# define	ICE_STORM_STRING	265
# define	ICE_STORM_SHOW	266
# define	ICE_STORM_COPYING	267
# define	ICE_STORM_WARRANTY	268


#endif /* not BISON_GRAMMAR_TAB_H */
