#ifndef YYSTYPE
#define YYSTYPE int
#endif
#define	ICE_STORM_HELP	257
#define	ICE_STORM_EXIT	258
#define	ICE_STORM_CREATE	259
#define	ICE_STORM_DESTROY	260
#define	ICE_STORM_LIST	261
#define	ICE_STORM_LINK	262
#define	ICE_STORM_UNLINK	263
#define	ICE_STORM_GRAPH	264
#define	ICE_STORM_STRING	265

