#ifndef BISON_GRAMMAR_TAB_H
# define BISON_GRAMMAR_TAB_H

# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
# define	TOK_HELP	257
# define	TOK_EXIT	258
# define	TOK_ADD_CONTACTS	259
# define	TOK_FIND_CONTACTS	260
# define	TOK_NEXT_FOUND_CONTACT	261
# define	TOK_PRINT_CURRENT	262
# define	TOK_SET_CURRENT_NAME	263
# define	TOK_SET_CURRENT_ADDRESS	264
# define	TOK_SET_CURRENT_PHONE	265
# define	TOK_REMOVE_CURRENT	266
# define	TOK_SET_EVICTOR_SIZE	267
# define	TOK_SHUTDOWN	268
# define	TOK_STRING	269


#endif /* not BISON_GRAMMAR_TAB_H */
