#ifndef BISON_GRAMMAR_TAB_H
# define BISON_GRAMMAR_TAB_H

# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
# define	ICE_PACK_HELP	257
# define	ICE_PACK_EXIT	258
# define	ICE_PACK_APPLICATION	259
# define	ICE_PACK_NODE	260
# define	ICE_PACK_SERVER	261
# define	ICE_PACK_ADAPTER	262
# define	ICE_PACK_PING	263
# define	ICE_PACK_ADD	264
# define	ICE_PACK_REMOVE	265
# define	ICE_PACK_LIST	266
# define	ICE_PACK_SHUTDOWN	267
# define	ICE_PACK_STRING	268
# define	ICE_PACK_START	269
# define	ICE_PACK_STOP	270
# define	ICE_PACK_DESCRIBE	271
# define	ICE_PACK_STATE	272
# define	ICE_PACK_PID	273
# define	ICE_PACK_ENDPOINTS	274
# define	ICE_PACK_ACTIVATION	275
# define	ICE_PACK_OBJECT	276
# define	ICE_PACK_FIND	277


#endif /* not BISON_GRAMMAR_TAB_H */
